# Generated by Django 4.2.1 on 2023-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='frame_data',
            field=models.ImageField(default='', upload_to='video_frames/'),
        ),
    ]
