# Generated by Django 4.2.1 on 2023-06-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_video_frame_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='frame_data',
        ),
    ]
